version: '3.9'

services:
  app_vue2:
    container_name: spa_app_vue2
    build: 
      context: ./app_vue2
      dockerfile: Dockerfile.dev
    volumes:
      - ./app_vue2/src:/opt/app/src
    ports:
      - 8081:8081
  
  app_vue3:
    container_name: spa_app_vue3
    build: 
      context: ./app_vue3
      dockerfile: Dockerfile.dev
    volumes:
      - ./app_vue3/src:/opt/app/src
    ports:
      - 8082:8082

  app_react:
    container_name: spa_app_react
    build: 
      context: ./app_react
      dockerfile: Dockerfile.dev
    volumes:
      - ./app_react/src:/opt/app/src
    ports:
      - 8083:3000

  server_vue3:
    container_name: spa_server_vue3
    build: 
      context: ./server_vue
      dockerfile: Dockerfile.dev
    volumes:
      - ./server_vue/src:/opt/app/src
    ports:
      - 8080:8080

  server_react:
    container_name: spa_server_react
    build: 
      context: ./server_react
      dockerfile: Dockerfile.dev
    volumes:
      - ./server_react/src:/opt/app/src
    ports:
      - 8030:3000
